---
- hosts: rackspace
  tasks:
    - ping: True
- hosts: troy
  vars:
    - set_hosts_file: yes
  vars_files:
    - [roles/troy/vars/secrets.yml, roles/troy/vars/main.yml]
  roles:
    - common
    - server
    - troy
