- name: Add Logstash repository
  apt_repository: repo="deb http://packages.elasticsearch.org/logstash/{{ logstash.version }}/debian stable main" state=present

- name: Add Logstash repository key
  apt_key: url="http://packages.elasticsearch.org/GPG-KEY-elasticsearch" state=present

- name: Install Logstash
  apt: pkg={{ item }} update_cache=yes state=latest
  with_items:
   - logstash
   - logstash-contrib

- name: Add the logstash user to the adm group
  user: name=logstash groups=adm append=yes

