- name: Add the docker repository key.
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D
  sudo: yes

- name: Add the docker PPA.
  copy: content="deb https://apt.dockerproject.org/repo ubuntu-trusty main" dest=/etc/apt/sources.list.d/docker.list
  sudo: yes

- name: Install docker.
  apt: pkg=docker-engine state=installed update-cache=yes
  sudo: yes

- name: Create discourse folder.
  file: path={{ discourse.root_path }} state=directory owner=www-data
  register: folder
  sudo: yes

- name: Clone discourse from GitHub repo
  git: repo=https://github.com/discourse/discourse_docker.git dest={{ discourse.root_path }}
  when: folder|changed
  sudo: yes
  sudo_user: www-data

# - name: setup discourse conf
#   template: src={{ discourse.app_conf }} dest={{ discourse.root_path }}/containers/app.yml owner={{ discourse.user }} force=yes

# - name: discourse installation
#   shell: echo -ne '\n' | /bin/bash launcher bootstrap app chdir={{ discourse.root_path }}
#   when: folder|changed

# - name: start application
#   shell: /bin/bash launcher start app chdir={{ discourse.root_path }}